<a href="https://colab.research.google.com/github/DanielleRodriguez/Danielle_Projects/blob/main/Copy_of_SudokuGameDanyRodriguez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random 
import pandas as pd


#solveInitial --> already solved sudoku board serving as a base for the randomly generated unsolved sudoku boards
#Going to manipulate it by swapping rows and columns as well as increasing every value by 1. 

solvedInitial = [[8, 2, 7, 1, 5, 4, 3, 9, 6, 9, 6, 5, 3, 2, 7, 1, 4, 8, 3, 4, 1, 6, 8, 9, 7, 5, 2, 5, 9, 3, 4, 6, 8, 2, 7, 1, 4, 7, 2, 5, 1, 3, 6, 8, 9, 6, 1, 8, 9, 7, 2, 4, 3, 5, 7, 8, 6, 2, 3, 5, 9, 1, 4, 1, 5, 4, 7, 9, 6, 8, 2, 3, 2, 3, 9, 8, 4, 1, 5, 6, 7]]

matrixSolved = np.array(solvedInitial) #converts list to array

solvedA = matrixSolved[0].reshape((9, 9)) #reshaping array so it is in 9x9 matrix form

print(solvedA)


[[8 2 7 1 5 4 3 9 6]
 [9 6 5 3 2 7 1 4 8]
 [3 4 1 6 8 9 7 5 2]
 [5 9 3 4 6 8 2 7 1]
 [4 7 2 5 1 3 6 8 9]
 [6 1 8 9 7 2 4 3 5]
 [7 8 6 2 3 5 9 1 4]
 [1 5 4 7 9 6 8 2 3]
 [2 3 9 8 4 1 5 6 7]]


In [ ]:
#Combination of row, column, and value increase. 
#eachBoard is an empty list that stores all of the new boards

eachBoard = [] #List where all uniquely generated sudoku boards are stored
step = 1 #value that each individual value is increased by 


for i in range(1,259):
    for j in range(0,i):
      rowSwap = np.roll(solvedA, -3, axis = 0) #first 3 rows moved to the bottom of matrix
      colSwap = np.roll(rowSwap, -3, axis = 1) #first 3 columns moved to right side of matrix
      newGrid = [x + step for x in colSwap] #This line of code increases each value by the step value

      x = np.asarray(newGrid) 
      reshaped_array = x.reshape(9,9).T #This line of code reshapes the array so that its in the form of a 9x9 grid
      reshaped_array[reshaped_array == 10] = 1 #This line of code takes every value that is 10 and replaces it with the value of 1.

      eachBoard.append(rowSwap) #These 3 lines of code appends the newly generated sudoku boards to the list, eachBoard so that they can be called later. 
      eachBoard.append(colSwap) 
      eachBoard.append(reshaped_array)

      solvedA = reshaped_array #I set solvedA equal to one of the newly generated sudoku boards so that it will continually loop through and keep generate new, unique, grids.

#print(eachBoard[0])
#print("")
#print(eachBoard[89])
#print("")
#print(eachBoard[78976])
#print(eachBoard[100232]) 
print(len(eachBoard))


100233


In [ ]:
from random import randrange

randVal = randrange(100000) #These 5 lines of code generate a random number to call a random grid from the list of grids stored in eachBoard. 

board1 = eachBoard[randVal]
board2 = eachBoard[randVal]
board3 = eachBoard[randVal]
board4 = eachBoard[randVal]


#else if statement so users can pick their desired level of difficulty.
user_input = input("Pick your level: 1, 2, 3, or 4: ")
print("")
print("You have picked Level", user_input)
print("")

if user_input == "1":
    print("Level 1 Solved:" )
    print(board1)

elif user_input == "2":
  print("Level 2 Solved:" )
  print(board2)

elif user_input == "3":
  print("Level 3 Solved:" )
  print(board3)

else:
  print("Level 4 Solved:" )
  print(board4)

print("---------------------")

unsolvedBoard1 = board1 
unsolvedBoard2 = board2 
unsolvedBoard3 = board3 
unsolvedBoard4 = board4 



#else if statement to remove random values of the board and replace them with 0

if user_input == "1":
    #indices_x1 = np.random.choice(range(unsolvedBoard1.shape[0]), 10)
    #indices_y1 = np.random.choice(range(unsolvedBoard1.shape[1]), 10)
    indices_x1 = np.random.randint(0, unsolvedBoard1.shape[0], 10)
    indices_y1 = np.random.randint(0, unsolvedBoard1.shape[1], 10)

    unsolvedBoard1[indices_x1, indices_y1] = 0
    print("Level 1 Unsolved:") 
    print(unsolvedBoard1)

elif user_input == "2":
    indices_x2 = np.random.choice(range(unsolvedBoard2.shape[0]), 30)
    indices_y2 = np.random.choice(range(unsolvedBoard2.shape[1]), 30)

    unsolvedBoard2[indices_x2, indices_y2] = 0
    print("Level 2 Unsolved:") 
    print(unsolvedBoard2)

elif user_input == "3":
    indices_x3 = np.random.choice(range(unsolvedBoard3.shape[0]), 70)
    indices_y3 = np.random.choice(range(unsolvedBoard3.shape[1]), 70)

    unsolvedBoard3[indices_x3, indices_y3] = 0 
    print("Level 3 Unsolved:") 
    print(unsolvedBoard3)

else:
    indices_x4 = np.random.choice(range(unsolvedBoard4.shape[0]), 150)
    indices_y4 = np.random.choice(range(unsolvedBoard4.shape[1]), 150)

    unsolvedBoard4[indices_x4, indices_y4] = 0
    print("Level 4 Unsolved:") 
    print(unsolvedBoard4)

Pick your level: 1, 2, 3, or 4: 2

You have picked Level 2

Level 2 Solved:
[[1 3 5 8 4 7 2 6 9]
 [2 7 9 3 5 6 1 4 8]
 [6 4 8 1 9 2 3 7 5]
 [8 9 2 6 7 1 4 5 3]
 [4 6 3 5 8 9 7 2 1]
 [5 1 7 2 3 4 8 9 6]
 [7 2 1 9 6 3 5 8 4]
 [9 8 4 7 1 5 6 3 2]
 [3 5 6 4 2 8 9 1 7]]
---------------------
Level 2 Unsolved:
[[0 3 5 8 4 7 2 0 9]
 [2 7 0 3 0 0 1 0 8]
 [6 4 8 1 9 0 3 0 5]
 [8 0 2 0 7 1 4 5 3]
 [4 6 3 0 8 0 0 2 1]
 [0 1 7 0 3 4 0 9 6]
 [7 2 1 9 0 0 0 8 4]
 [0 8 4 0 1 5 6 0 0]
 [0 5 6 0 2 0 9 1 7]]
